import { EventBus } from "./Bus.js";
import "./DataDrivenEntityTrigger.js";
import "./EntityDie.js";
import "./EntityHealthChanged.js";
import "./EntityHurtBefore.js";
import "./EntityHurtAfter.js";
import "./EntityRemove.js";
import "./EntitySpawn.js";
import "./ScriptEventReceive.js";
import "./Reload.js";
export const gameEvents = new EventBus();
export const debug = gameEvents.debug.bind(gameEvents);
export const debugLocal = (target) => gameEvents.debug(target);
export const subscribe = gameEvents.subscribe.bind(gameEvents);
export const once = gameEvents.once.bind(gameEvents);
export const unsubscribe = gameEvents.unsubscribe.bind(gameEvents);
export const unsubscribeAll = gameEvents.unsubscribeAll.bind(gameEvents);
export const block = gameEvents.block.bind(gameEvents);
export const unblock = gameEvents.unblock.bind(gameEvents);
export const pauseAll = gameEvents.pauseAll.bind(gameEvents);
export const resumeAll = gameEvents.resumeAll.bind(gameEvents);
export const migrate = gameEvents.migrate.bind(gameEvents);
export const publish = gameEvents.publish.bind(gameEvents);
