export { MobProfiles } from "./entities/index.js";
export { ManagedEntity } from "./ManagedEntity.js";
export { ComponentIds } from "./components/Component.js";
export { DamageComponent } from "./components/Damage.js";
export { EquipmentComponent } from "./components/Equipment.js";
export { HealthComponent } from "./components/Health.js";
export { InventoryComponent } from "./components/Inventory.js";
export { SpawnEntityComponent } from "./components/SpawnEntity.js";
export { SpawnRulesComponent, assignSpawnProfile } from "./components/SpawnRules.js";
export { LootableComponent, LootTables } from "./components/Lootable.js";
export { LevelComponent, ScalarComponent } from "./components/Scalar.js";
export { NameTagComponent } from "./components/NameTag.js";
export { defineEntityProfiles, defineEntityProfile } from "./Profiles.js";
export { ComponentRegistry } from "./components/Registry.js";
export { EntityRegistry } from "./Registry.js";
export { EntityStore } from "./storage/index.js";
export { AGGRESSIVE_MOBS, PASSIVE_MOBS, assertDamageComponentAccess, canAccessDamageComponent, getMobDisposition, } from "./Combat.js";
export { createSpawnEgg, giveSpawnEgg, showSpawnEggMenu, } from "./SpawnEggs.js";
export { cloneItemStack, deserializeItemStack, serializeItemStack, } from "../mc_dependencies/storage/ItemStack.js";
